name: Cut Scheduled Release

# on: 
#   schedule:
#     - cron: '0 5 * * 5' # Run the job at 5PM every Friday
on:
  push:
    branches:
      - 'development'

jobs:
  cut_latest_release_branch:
    name: Cut the latest release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Development
      uses: actions/checkout@v1 #checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: Get Last Branch and Semantic Version Containing String
      id: lrb
      uses: jessicalostinspace/github-action-get-regex-branch@v1.0.0
      with:
        regex-string: 'release-v' 
    - name: Get Bumped Semantic Version
      id: bsv
      uses: ./
      with:
        semantic-version: ${{ steps.lrb.outputs.last-semver }}
        version-type: 'Minor'
